language: ruby
rvm:
  - 2.1.2
before_deploy:
  - rvm list
deploy:
  provider: heroku
  strategy: api
  api_key:
<<<<<<< HEAD
    secure: fkXeCZI+G9XpLOk2HipySjNssS9d74Jc7PXno2dDtZ2SVDjlsZMd7FY+mGoAeyK02eCvzE5ldg0b2IuJPEl3MJF301kAx4g9QSubUYe5dzEY7G9jDM9cIqWzd8qgQvxBBUcZ66vwB6KSoPQEJdwEOd1Hujf7foMUFDO3ICOC7es=
  app:
    master: hidden-garden-3599
    production: pacific-dawn-8716
=======
    secure: Qh1bRuZGjAgvXNnQIli5ZN8D9AUgQUXz6gD8MlyN3aX7B2XJjHbQa446FZpgE33+r4dRkGqbzkMNgu4NTXoEoEl1+XYPCCBZ8arW79JVDa6RnvWpre9AvPj4VehCLVJPrqXIhXCQDGxfGHO2+6PQhrVDbhHh069h1QhqWxkjDns=
  app: hidden-garden-3599
>>>>>>> merge signin and signup page
  run:
    - "bundle exec --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment bundle install"
    - "bundle exec --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment rake db:migrate"
    - restart
    - "bundle exec --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment rake cleanup"
  on:
    repo: SocioQuiz/socio_quiz
<<<<<<< HEAD
#    rvm: 2.1.2
=======
>>>>>>> merge signin and signup page
